# Generated by Django 3.0.7 on 2022-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_items',
            name='distributor_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='distributor_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
