# Generated by Django 3.0.7 on 2022-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0003_auto_20220209_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_transaction',
            name='damaged_items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='goods_receipt_note',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='goods_return_note',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='quantity_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
